apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-metrics
  namespace: microservices
spec:
  metrics:
    - providers:
        - name: prometheus
    - overrides:
        - match:
            metric: ALL_METRICS
          tagOverrides:
            destination_service_name:
              value: '{{.destination_service_name | default "unknown"}}'
            source_service_name:
              value: '{{.source_service_name | default "unknown"}}'
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-tracing
  namespace: microservices
spec:
  tracing:
    - providers:
        - name: jaeger
    - randomSamplingPercentage: 100.0
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-access-log
  namespace: microservices
spec:
  accessLogging:
    - providers:
        - name: otel
    - format: |
        {
          "timestamp": "%START_TIME%",
          "method": "%REQ(:METHOD)%",
          "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
          "status": "%RESPONSE_CODE%",
          "duration": "%DURATION%",
          "user_agent": "%REQ(USER-AGENT)%",
          "request_id": "%REQ(X-REQUEST-ID)%",
          "upstream_service": "%UPSTREAM_CLUSTER%"
        }
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: observability-config
  namespace: istio-system
spec:
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            metric_relabeling_configs:
              - source_labels: [__name__]
                regex: "istio_build"
                target_label: __tmp_istio_build
              - source_labels: [__tmp_istio_build]
                target_label: version
        enabled: true
    pilot:
      traceSampling: 100.0
    global:
      meshConfig:
        extensionProviders:
          - name: jaeger
            envoyOtelAls:
              service: jaeger-collector.observability.svc.cluster.local
              port: 14250
          - name: prometheus
            prometheus:
              configOverride:
                metric_relabeling_configs:
                  - source_labels: [__name__]
                    regex: "istio_request_total"
                    target_label: __tmp_istio_request_total
        defaultProviders:
          metrics:
            - prometheus
          tracing:
            - jaeger
          accessLogging:
            - otel
