apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.50
          ports:
            - containerPort: 16686 # Jaeger UI
            - containerPort: 14268 # HTTP collector
            - containerPort: 14250 # gRPC collector
            - containerPort: 6831 # UDP agent
            - containerPort: 6832 # UDP agent
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  type: LoadBalancer
  ports:
    - port: 16686
      targetPort: 16686
      name: ui
    - port: 14268
      targetPort: 14268
      name: collector-http
    - port: 14250
      targetPort: 14250
      name: collector-grpc
    - port: 6831
      targetPort: 6831
      protocol: UDP
      name: agent-udp-thrift-compact
    - port: 6832
      targetPort: 6832
      protocol: UDP
      name: agent-udp-thrift-binary
    - port: 9411
      targetPort: 9411
      name: zipkin
  selector:
    app: jaeger
