# Elasticsearch Configuration
# Main configuration for Elasticsearch cluster

cluster.name: "kubernetes-logging"
node.name: "${HOSTNAME}"
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery configuration
discovery.seed_hosts: ["elasticsearch-master"]
cluster.initial_master_nodes: ["elasticsearch-master-0"]

# Node roles
node.master: true
node.data: true
node.ingest: true

# Memory and performance settings
bootstrap.memory_lock: true
indices.memory.index_buffer_size: 30%
indices.memory.min_index_buffer_size: 96mb

# Index settings
action.auto_create_index: true
action.destructive_requires_name: true

# Logging
logger.level: INFO
logger.org.elasticsearch.discovery: WARN

# Index lifecycle management
xpack.ilm.enabled: true

# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

# Security (uncomment for production)
# xpack.security.enabled: true
# xpack.security.transport.ssl.enabled: true
# xpack.security.http.ssl.enabled: true

# Thread pool settings
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000

# Circuit breaker settings
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 40%

# Recovery settings
cluster.routing.allocation.node_concurrent_recoveries: 2
indices.recovery.max_bytes_per_sec: 100mb

# Shard allocation
cluster.routing.allocation.total_shards_per_node: 1000
cluster.max_shards_per_node: 1000

# Index templates
index.number_of_shards: 1
index.number_of_replicas: 1
index.refresh_interval: 30s
index.translog.flush_threshold_size: 512mb
