# AlertManager Configuration
# Configure routing and notification channels for alerts

global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "alerts@yourcompany.com"
  smtp_auth_username: "alerts@yourcompany.com"
  smtp_auth_password: "your-app-password"

route:
  group_by: ["alertname", "cluster", "service"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "default"
  routes:
    - match:
        severity: critical
      receiver: "critical-alerts"
      group_wait: 5s
      repeat_interval: 30m

    - match:
        severity: warning
      receiver: "warning-alerts"
      group_wait: 30s
      repeat_interval: 4h

    - match_re:
        service: ^(user-service|payment-service)$
      receiver: "business-critical"
      group_wait: 5s
      repeat_interval: 15m

receivers:
  - name: "default"
    email_configs:
      - to: "devops@yourcompany.com"
        subject: "Alert: {{ .GroupLabels.alertname }}"
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}: {{ .Value }}{{ end }}
          {{ end }}

  - name: "critical-alerts"
    email_configs:
      - to: "oncall@yourcompany.com,devops@yourcompany.com"
        subject: "CRITICAL: {{ .GroupLabels.alertname }}"
        body: |
          CRITICAL ALERT TRIGGERED

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}

          Labels: {{ range .Labels.SortedPairs }}
          - {{ .Name }}: {{ .Value }}{{ end }}
          {{ end }}

    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#alerts-critical"
        title: "CRITICAL Alert: {{ .GroupLabels.alertname }}"
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        color: "danger"

  - name: "warning-alerts"
    email_configs:
      - to: "devops@yourcompany.com"
        subject: "Warning: {{ .GroupLabels.alertname }}"
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#alerts-warning"
        title: "Warning: {{ .GroupLabels.alertname }}"
        text: |
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ end }}
        color: "warning"

  - name: "business-critical"
    email_configs:
      - to: "business@yourcompany.com,oncall@yourcompany.com"
        subject: "Business Critical Service Alert: {{ .GroupLabels.alertname }}"
        body: |
          A business critical service is experiencing issues.

          {{ range .Alerts }}
          Service: {{ .Labels.service }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

          Please investigate immediately.

    pagerduty_configs:
      - service_key: "YOUR-PAGERDUTY-SERVICE-KEY"
        description: "{{ .GroupLabels.alertname }}: {{ .GroupLabels.service }}"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "cluster", "service"]

  - source_match:
      alertname: "ServiceDown"
    target_match_re:
      alertname: "^(HighErrorRate|HighLatency)$"
    equal: ["service"]
