apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: tracing
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_binary:
            endpoint: 0.0.0.0:6832

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      memory_limiter:
        limit_mib: 512

    exporters:
      jaeger:
        endpoint: jaeger-collector.tracing.svc.cluster.local:14250
        tls:
          insecure: true
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [memory_limiter, batch]
          exporters: [jaeger, logging]
      
      extensions: [health_check, pprof, zpages]
      
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: tracing
  labels:
    app: otel-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.89.0
          ports:
            - containerPort: 4317 # OTLP gRPC receiver
            - containerPort: 4318 # OTLP HTTP receiver
            - containerPort: 14250 # Jaeger gRPC
            - containerPort: 14268 # Jaeger HTTP
            - containerPort: 6831 # Jaeger compact
            - containerPort: 6832 # Jaeger binary
            - containerPort: 13133 # Health check
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otel-collector-config.yaml
              subPath: config.yaml
          command:
            - /otelcol-contrib
            - --config=/etc/otel-collector-config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: tracing
  labels:
    app: otel-collector
spec:
  ports:
    - port: 4317
      name: otlp-grpc
    - port: 4318
      name: otlp-http
    - port: 14250
      name: jaeger-grpc
    - port: 14268
      name: jaeger-http
    - port: 6831
      name: jaeger-compact
      protocol: UDP
    - port: 6832
      name: jaeger-binary
      protocol: UDP
    - port: 13133
      name: health-check
  selector:
    app: otel-collector
