apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686
              name: ui
            - containerPort: 14268
              name: collector
            - containerPort: 6831
              name: agent-compact
              protocol: UDP
            - containerPort: 6832
              name: agent-binary
              protocol: UDP
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: observability
  labels:
    app: jaeger
spec:
  ports:
    - port: 14268
      targetPort: 14268
      name: collector
    - port: 9411
      targetPort: 9411
      name: zipkin
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: observability
  labels:
    app: jaeger
spec:
  ports:
    - port: 6831
      targetPort: 6831
      name: agent-compact
      protocol: UDP
    - port: 6832
      targetPort: 6832
      name: agent-binary
      protocol: UDP
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  namespace: observability
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
    - port: 16686
      targetPort: 16686
      nodePort: 30686
      name: ui
  selector:
    app: jaeger
