#!/bin/bash

echo "🌐 Microservices Access URLs"
echo "============================"

# Get gateway port
GATEWAY_PORT=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')

echo "📊 Available Services and URLs:"
echo ""
echo "🔗 Istio Gateway (HTTP): http://localhost:$GATEWAY_PORT"
echo "   - Host header required: microservices.local"
echo ""
echo "🏪 Product Service:"
echo "   - Direct: http://localhost:30000 (via API Gateway)"
echo "   - Via Istio: http://localhost:$GATEWAY_PORT/product/health"
echo "   - Headers: -H 'Host: microservices.local'"
echo ""
echo "📦 Order Service:"
echo "   - Direct: http://localhost:30003"
echo "   - Via Istio: http://localhost:$GATEWAY_PORT/order/health"
echo "   - Headers: -H 'Host: microservices.local'"
echo ""
echo "🖥️  Frontend:"
echo "   - Direct: http://localhost:30080"
echo "   - Via Istio: http://localhost:$GATEWAY_PORT/"
echo "   - Headers: -H 'Host: frontend.local'"
echo ""
echo "🔐 Auth Service:"
echo "   - Direct: http://localhost:30001"
echo ""
echo "🌟 API Gateway:"
echo "   - Direct: http://localhost:30000"
echo "   - Via Istio: http://localhost:$GATEWAY_PORT/api/"
echo "   - Headers: -H 'Host: microservices.local'"
echo ""
echo "📈 Kiali Dashboard: http://localhost:20001"
echo "📊 Grafana Dashboard: http://localhost:3000"
echo "🔍 Jaeger Tracing: http://localhost:16686"
echo ""
echo "🧪 Quick Tests:"
echo "curl -H 'Host: microservices.local' http://localhost:$GATEWAY_PORT/product/health"
echo "curl -H 'Host: microservices.local' http://localhost:$GATEWAY_PORT/order/health"
echo "curl http://localhost:30003/health"
echo "curl http://localhost:30080"
