apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
    monitoring: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        monitoring: prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: product-service
        image: node:18-alpine
        command: ["node", "-e"]
        args:
          - |
            const http = require('http');
            const url = require('url');
            
            const products = [
              { id: 1, name: 'Laptop', price: 999.99, category: 'Electronics' },
              { id: 2, name: 'Coffee Mug', price: 19.99, category: 'Home' },
              { id: 3, name: 'Book', price: 9.99, category: 'Education' }
            ];
            
            const server = http.createServer((req, res) => {
              const parsedUrl = url.parse(req.url, true);
              
              res.setHeader('Access-Control-Allow-Origin', '*');
              res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
              res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
              res.setHeader('Content-Type', 'application/json');
              
              if (req.method === 'OPTIONS') {
                res.writeHead(200);
                res.end();
                return;
              }
              
              if (parsedUrl.pathname === '/health') {
                res.writeHead(200);
                res.end(JSON.stringify({
                  service: 'product-service',
                  status: 'healthy',
                  timestamp: new Date().toISOString()
                }));
              } else if (parsedUrl.pathname === '/products') {
                res.writeHead(200);
                res.end(JSON.stringify(products));
              } else if (parsedUrl.pathname.startsWith('/products/')) {
                const id = parseInt(parsedUrl.pathname.split('/')[2]);
                const product = products.find(p => p.id === id);
                if (product) {
                  res.writeHead(200);
                  res.end(JSON.stringify(product));
                } else {
                  res.writeHead(404);
                  res.end(JSON.stringify({ error: 'Product not found' }));
                }
              } else {
                res.writeHead(404);
                res.end(JSON.stringify({ error: 'Not found' }));
              }
            });
            
            server.listen(3002, () => {
              console.log('Product Service listening on port 3002');
            });
              { id: 2, name: 'Smartphone', price: 599.99, category: 'Electronics' },
              { id: 3, name: 'Coffee Mug', price: 12.99, category: 'Home' }
            ];

            // Metrics
            const httpRequestsTotal = new client.Counter({
              name: 'http_requests_total',
              help: 'Total HTTP requests',
              labelNames: ['method', 'route', 'status'],
              registers: [register]
            });

            // Jaeger tracing
            const config = {
              serviceName: 'product-service',
              reporter: {
                collectorEndpoint: 'http://jaeger-collector.observability.svc.cluster.local:14268/api/traces'
              }
            };
            const tracer = jaeger.initTracer(config);

            // Middleware
            app.use(express.json());
            app.use((req, res, next) => {
              res.on('finish', () => {
                httpRequestsTotal.inc({ method: req.method, route: req.path, status: res.statusCode });
              });
              next();
            });

            // Routes
            app.get('/health', (req, res) => {
              res.json({ service: 'product-service', status: 'healthy', timestamp: new Date().toISOString() });
            });

            app.get('/metrics', (req, res) => {
              res.set('Content-Type', register.contentType);
              res.end(register.metrics());
            });

            app.get('/products', (req, res) => {
              res.json(products);
            });

            app.get('/products/:id', (req, res) => {
              const product = products.find(p => p.id === parseInt(req.params.id));
              if (product) {
                res.json(product);
              } else {
                res.status(404).json({ error: 'Product not found' });
              }
            });

            // Start servers
            app.listen(3002, () => console.log('Product Service listening on port 3002'));
            
            // Metrics server
            const metricsApp = express();
            metricsApp.get('/metrics', (req, res) => {
              res.set('Content-Type', register.contentType);
              res.end(register.metrics());
            });
            metricsApp.listen(9090, () => console.log('Metrics server listening on port 9090'));
            EOF
            
            node app.js
        ports:
        - containerPort: 3002
          name: http
        - containerPort: 9090
          name: metrics
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep 'node app.js' | grep -v grep"
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh  
            - -c
            - "ps aux | grep 'node app.js' | grep -v grep"
          initialDelaySeconds: 90
          periodSeconds: 5
        env:
        - name: SERVICE_NAME
          value: "product-service"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
    monitoring: prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30002
    name: http
  - port: 9090
    targetPort: 9090
    name: metrics
  selector:
    app: product-service
