apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres.microservices.svc.cluster.local:5432/postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "postgres"
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
  NODE_ENV: "production"
  REDIS_URL: "redis://redis.microservices.svc.cluster.local:6379"
  REDIS_HOST: "redis.microservices.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "kafka.kafka.svc.cluster.local:9092"
  AUTH_SERVICE_URL: "http://auth-service.microservices.svc.cluster.local:3001"
  ORDER_SERVICE_URL: "http://order-service.microservices.svc.cluster.local:3003"
  PRODUCT_SERVICE_URL: "http://product-service.microservices.svc.cluster.local:8080"
