server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: product-service
    
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres.microservices.svc.cluster.local}:${DB_PORT:5432}/${DB_NAME:products}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    
  security:
    jwt:
      secret: ${JWT_SECRET:your-secret-key}
      expiration: ${JWT_EXPIRATION:86400}

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Application info
info:
  app:
    name: ${spring.application.name}
    description: Product catalog microservice
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}

# Logging configuration
logging:
  level:
    com.microservices.productservice: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_PARAM_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/product-service.log
    
# Custom application properties
app:
  name: Product Service
  version: 1.0.0
  description: Microservice for managing product catalog
  api:
    version: v1
    base-path: /api/products