apiVersion: v1
kind: Pod
metadata:
  name: security-pod-example
  namespace: microservices
spec:
  serviceAccountName: api-gateway-sa
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: api-gateway
      image: your-registry/api-gateway:latest
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
          add:
            - NET_BIND_SERVICE
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
          ephemeral-storage: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 100Mi
      volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: var-cache
          mountPath: /var/cache
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: secret-volume
          mountPath: /app/secrets
          readOnly: true
      env:
        - name: NODE_ENV
          value: "production"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: jwt-secret
      ports:
        - containerPort: 3000
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /health
          port: 3000
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /ready
          port: 3000
        initialDelaySeconds: 5
        periodSeconds: 5
  volumes:
    - name: tmp-volume
      emptyDir: {}
    - name: var-cache
      emptyDir: {}
    - name: config-volume
      configMap:
        name: security-config
    - name: secret-volume
      secret:
        secretName: api-secrets
        defaultMode: 0400
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: microservices-pdb
  namespace: microservices
spec:
  minAvailable: 1
  selector:
    matchLabels:
      tier: microservice
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: microservices-quota
  namespace: microservices
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: microservices-limits
  namespace: microservices
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 100Mi
      max:
        cpu: 2
        memory: 4Gi
        ephemeral-storage: 5Gi
      min:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 50Mi
      type: Container
    - default:
        storage: 10Gi
      max:
        storage: 50Gi
      min:
        storage: 1Gi
      type: PersistentVolumeClaim
