apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-reader
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: microservices
  name: microservices-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-microservices
  namespace: microservices
subjects:
  - kind: ServiceAccount
    name: microservices-reader
    namespace: microservices
roleRef:
  kind: Role
  name: microservices-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-service-account
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-cluster-reader
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "services", "endpoints", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-cluster-reader
subjects:
  - kind: ServiceAccount
    name: monitoring-service-account
    namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: microservices
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: microservices
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-sa
  namespace: microservices
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: microservices
  name: service-basic-access
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-binding
  namespace: microservices
subjects:
  - kind: ServiceAccount
    name: api-gateway-sa
    namespace: microservices
roleRef:
  kind: Role
  name: service-basic-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-binding
  namespace: microservices
subjects:
  - kind: ServiceAccount
    name: auth-service-sa
    namespace: microservices
roleRef:
  kind: Role
  name: service-basic-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-service-binding
  namespace: microservices
subjects:
  - kind: ServiceAccount
    name: product-service-sa
    namespace: microservices
roleRef:
  kind: Role
  name: service-basic-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: order-service-binding
  namespace: microservices
subjects:
  - kind: ServiceAccount
    name: order-service-sa
    namespace: microservices
roleRef:
  kind: Role
  name: service-basic-access
  apiGroup: rbac.authorization.k8s.io
