# Microservices ServiceMonitor for Prometheus
# This enables automatic discovery and scraping of your microservices

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  namespace: monitoring
  labels:
    app: microservices
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: microservice
  namespaceSelector:
    matchNames:
      - microservices
      - staging
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
    - port: http
      path: /metrics
      interval: 30s
    - port: web
      path: /metrics
      interval: 30s

---
# Alternative ServiceMonitor for services with standard ports
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-by-annotation
  namespace: monitoring
  labels:
    app: microservices-annotation
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
  namespaceSelector:
    matchNames:
      - microservices
      - staging
      - gitops
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      honorLabels: true
    - targetPort: 8080
      path: /metrics
      interval: 30s
    - targetPort: 3000
      path: /metrics
      interval: 30s
    - targetPort: 3001
      path: /metrics
      interval: 30s
    - targetPort: 3003
      path: /metrics
      interval: 30s

---
# ServiceMonitor for specific microservices
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
  namespace: monitoring
  labels:
    app: api-gateway
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-gateway
  namespaceSelector:
    matchNames:
      - microservices
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
    - targetPort: 3000
      path: /metrics
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: monitoring
  labels:
    app: auth-service
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: auth-service
  namespaceSelector:
    matchNames:
      - microservices
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
    - targetPort: 3001
      path: /metrics
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-monitor
  namespace: monitoring
  labels:
    app: product-service
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: product-service
  namespaceSelector:
    matchNames:
      - microservices
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
    - targetPort: 8080
      path: /metrics
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-monitor
  namespace: monitoring
  labels:
    app: order-service
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: order-service
  namespaceSelector:
    matchNames:
      - microservices
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
    - targetPort: 3003
      path: /metrics
      interval: 15s
