global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
