# Jaeger Production Configuration
# Production-ready Jaeger deployment with separate components

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger
    component: collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jaeger
      component: collector
  template:
    metadata:
      labels:
        app: jaeger
        component: collector
    spec:
      containers:
        - name: jaeger-collector
          image: jaegertracing/jaeger-collector:1.46
          args:
            - --config-file=/conf/collector.yaml
          ports:
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /conf
          env:
            - name: SPAN_STORAGE_TYPE
              value: elasticsearch
            - name: ES_SERVER_URLS
              value: http://elasticsearch.logging.svc.cluster.local:9200
            - name: ES_INDEX_PREFIX
              value: jaeger
      volumes:
        - name: config
          configMap:
            name: jaeger-collector-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-collector-config
  namespace: monitoring
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          http:
            endpoint: 0.0.0.0:14268
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_binary:
            endpoint: 0.0.0.0:6832
      zipkin:
        endpoint: 0.0.0.0:9411

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      
    exporters:
      elasticsearch:
        endpoints: [http://elasticsearch.logging.svc.cluster.local:9200]
        index: jaeger-span
        mapping:
          enabled: true

    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger, zipkin]
          processors: [batch]
          exporters: [elasticsearch]

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent
  namespace: monitoring
  labels:
    app: jaeger
    component: agent
spec:
  selector:
    matchLabels:
      app: jaeger
      component: agent
  template:
    metadata:
      labels:
        app: jaeger
        component: agent
    spec:
      containers:
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:1.46
          args:
            - --config-file=/conf/agent.yaml
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: config
              mountPath: /conf
          env:
            - name: REPORTER_GRPC_HOST_PORT
              value: jaeger-collector:14250
      volumes:
        - name: config
          configMap:
            name: jaeger-agent-config
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-agent-config
  namespace: monitoring
data:
  agent.yaml: |
    reporter:
      grpc:
        host-port: jaeger-collector:14250

    processor:
      jaeger-compact:
        server-queue-size: 1000
        server-max-packet-size: 65000
        server-host-port: :6831
        workers: 10
      
      jaeger-binary:
        server-queue-size: 1000
        server-max-packet-size: 65000
        server-host-port: :6832
        workers: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: monitoring
  labels:
    app: jaeger
    component: query
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jaeger
      component: query
  template:
    metadata:
      labels:
        app: jaeger
        component: query
    spec:
      containers:
        - name: jaeger-query
          image: jaegertracing/jaeger-query:1.46
          args:
            - --config-file=/conf/query.yaml
          ports:
            - containerPort: 16686
              protocol: TCP
            - containerPort: 16687
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: config
              mountPath: /conf
          env:
            - name: SPAN_STORAGE_TYPE
              value: elasticsearch
            - name: ES_SERVER_URLS
              value: http://elasticsearch.logging.svc.cluster.local:9200
            - name: ES_INDEX_PREFIX
              value: jaeger
      volumes:
        - name: config
          configMap:
            name: jaeger-query-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-query-config
  namespace: monitoring
data:
  query.yaml: |
    http-server:
      host-port: :16686

    grpc-server:
      host-port: :16687

    query:
      additional-headers:
        - X-Frame-Options:DENY
        - X-Content-Type-Options:nosniff
      ui-config: /conf/ui.json
      log-level: info

  ui.json: |
    {
      "monitoring": {
        "menuEnabled": true
      },
      "dependencies": {
        "menuEnabled": true
      },
      "archiveEnabled": true,
      "tracking": {
        "gaID": "",
        "trackErrors": true
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger
    component: collector
spec:
  ports:
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: jaeger-collector-grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    app: jaeger
    component: collector
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitoring
  labels:
    app: jaeger
    component: query
spec:
  ports:
    - name: query-http
      port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app: jaeger
    component: query
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: monitoring
  labels:
    app: jaeger
    component: agent
spec:
  ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: agent-configs
      port: 5778
      protocol: TCP
      targetPort: 5778
  clusterIP: None
  selector:
    app: jaeger
    component: agent
