apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: microservices
type: Opaque
data:
  username: bW9uZ29hZG1pbg==  # mongoadmin
  password: cGFzc3dvcmQxMjM=  # password123
  database: bWljcm9zZXJ2aWNlcw==  # microservices
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: microservices
type: Opaque
data:
  secret: c3VwZXJfc2VjcmV0X2p3dF9rZXlfZm9yX21pY3Jvc2VydmljZXM=  # super_secret_jwt_key_for_microservices
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: microservices
type: Opaque
data:
  external-api-key: YWJjZGVmZ2hpams=  # abcdefghijk
  internal-api-key: bG1ub3BxcnN0dXZ3eHl6  # lmnopqrstuvwxyz
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
  namespace: microservices
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: microservices
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==
