# Grafana Datasources Configuration
# This file configures automatic datasource provisioning

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-stack-kube-prom-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "300s"
      httpMethod: POST

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch.logging.svc.cluster.local:9200
    database: "kubernetes-*"
    editable: true
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "7.10.0"
      includeFrozen: false
      logMessageField: "message"
      logLevelField: "level"

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query.monitoring.svc.cluster.local:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: "elasticsearch"
        tags: ["job", "instance", "pod", "namespace"]
        mappedTags: [{ "key": "service.name", "value": "service" }]
        mapTagNamesEnabled: false
        spanStartTimeShift: "1h"
        spanEndTimeShift: "1h"
        filterByTraceID: false
        filterBySpanID: false
